In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import molmodmt as m3t
import simtk.openmm as mm
import simtk.unit as unit
import simtk.openmm.app as app
import numpy as np

/home/diego/Myopt/Miniconda/miniconda3/envs/UIBCDF_lab_dev/lib/python3.7/site-packages/yank/experiment.py:1161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  """)


In [9]:
system = m3t.load('fin.pdb','mdtraj')

In [10]:
system_ref = m3t.load('../MisL_PepFus_memb.pdb','mdtraj')

In [11]:
system_ref_prot = m3t.extract(system_ref, "protein")

In [19]:
m3t.select(system,selection="resid 0 and name C N CA O")

array([0, 4, 6, 7])

In [20]:
m3t.select(system,selection="resid 0 and name C N CA O")

array([0, 4, 6, 7])

In [26]:
m3t.select(system_ref_prot,selection="residue 82 and name C N CA O")

array([1107, 1108, 1109, 1110])

In [28]:
m3t.least_rmsd_fit(system, system_ref_prot, "resid 0 and name C N CA O", "residue 82 and name C N CA O", engine="mdtraj")

In [31]:
pepfus = m3t.extract(system_ref_prot, "residue 1 to 82")

In [36]:
ensamblado = m3t.merge([pepfus,system])

In [37]:
m3t.view(ensamblado)

NGLWidget()

In [38]:
m3t.convert(ensamblado,"ensamblado.pdb")

In [ ]:
view = m3t.view(system)
view

In [ ]:
atoms_sel = m3t.select(system, 'resid 0 and name CA')

for ii in atoms_sel:
    arrow_init = positions[ii]._value*10
    vect_to_pull = np.array([0.0, -10.0, 0.0])
    arrow_end = arrow_init + vect_to_pull
    view.shape.add_arrow(arrow_init, arrow_end, [1.0, 0.0, 0.0], 1.0, 'F')

In [ ]:
m3t.distances(system,selection=0,selection2=100).shape

In [ ]:
system